version: '3.8'

services:
  spring-app:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - ./target/demo-0.0.1-SNAPSHOT.jar:/app/demo.jar
    command: ["java", "-jar", "/app/demo.jar"]
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ReserQ?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: cos1234
    networks:
      - backend

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ReserQ
      MYSQL_USER: root
      MYSQL_PASSWORD: cos1234
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge