version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: cos1234
      MYSQL_DATABASE: ReserQ
    ports:
      - "3306:3306"
    command: --serverTimezone=Asia/Seoul --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --allowPublicKeyRetrieval=true --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

  app:
    image: openjdk:11-jre-slim
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ReserQ?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: cos1234
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./path/to/your/application.jar:/app.jar

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
